CustomResourceDefinition v1 schema
alexellis/registry-creds pull request #33
Opened 2021-04-14 12:15 UTC by dfateyev

This PR addresses two issues:
- Migration CustomResourceDefinition to "apiextensions.k8s.io/v1" schema (k8s 1.19+ warn about "apiextensions.k8s.io/v1beta1" deprecation);
- Small manifest cleanup.

Tested under 1.19.8, the improved version works for me.

2021-08-21 14:27 UTC, billimek commented
This is [required](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122) to continue to allow registry-creds to work under Kubernetes 1.22 which has already been released.  Any chance we can get this merged, @alexellis?

2021-12-09 13:39 UTC, alexellis commented
@billimek any chance you would become a GitHub Sponsor? I realise you will be using this at work, so it only seems fair.

2021-12-09 13:40 UTC, alexellis commented on manifest.yaml
> +apiVersion: apiextensions.k8s.io/v1
This file should be generated, not edited manually.

The change needs to happen in the codegen

2021-12-09 13:40 UTC, alexellis requested changes
Please see comment

2021-12-09 13:42 UTC, closed without merging